import { lazy, Suspense, useMemo, useRef, useState } from 'react';
import { MotionForge, type MotionForgeHandle } from 'motion-forge/react';
import { createPreset, presetCatalog, type PresetId } from 'motion-forge/presets';
import { Docs } from './Docs';
const StudioRoute = lazy(() => import('./StudioRoute'));
function Brand() { return <a className="site-brand" href="/" aria-label="Motion Forge home"><span className="site-mark">m<span>f</span></span><span>motion forge<span className="brand-dot">●</span></span></a>; }
function Navigation({ path }: { path: string }) { return <header className="site-nav"><Brand/><nav aria-label="Main"><a href="/examples/" aria-current={path.startsWith('/examples') ? 'page' : undefined}>Examples</a><a href="/docs/" aria-current={path.startsWith('/docs') ? 'page' : undefined}>Documentation</a><a className="nav-studio" href="/studio/">Open Studio <span>↗</span></a></nav></header>; }
function Showcase({ id, hero = false }: { id: PresetId; hero?: boolean }) {
  const doc = useMemo(() => createPreset(id), [id]); const player = useRef<MotionForgeHandle>(null); const [intensity, setIntensity] = useState(62), [confirmed, setConfirmed] = useState(false), [paused, setPaused] = useState(false);
  const preset = presetCatalog.find(p => p.id === id)!;
  return <div className={`showcase ${hero ? 'showcase-hero' : ''}`}><div className="showcase-label"><span>{preset.category.toUpperCase()} / {id === 'scout' ? '01' : id === 'made-it' ? '02' : '03'}</span><span className="live-label"><i/> LIVE VECTOR</span></div><MotionForge ref={player} document={doc} autoplay={!paused} inputs={id === 'signal' ? { intensity } : undefined} style={{ width: '100%', display: 'block' }}/><div className="showcase-controls">{id === 'signal' ? <label>Intensity <input type="range" min="0" max="100" value={intensity} onChange={e => setIntensity(Number(e.target.value))}/><output>{intensity}</output></label> : <button onClick={() => { if (id === 'scout') { setPaused(false); player.current?.send('wave'); } else { player.current?.send(confirmed ? 'reset' : 'confirm'); setConfirmed(v => !v); } }}>{id === 'scout' ? 'Say hello' : confirmed ? 'Try again' : 'Make it happen'} <span>↗</span></button>}<span>Go on. It’s interactive.</span>{id === 'scout' ? <button className="showcase-pause" aria-label={paused ? 'Play Scout animation' : 'Pause Scout animation'} onClick={() => setPaused(v => !v)}>{paused ? '▶' : 'Ⅱ'}</button> : null}</div></div>;
}
function Home() {
  return <><section className="hero"><div className="hero-copy"><span className="eyebrow"><i/> OPEN SOURCE. OPEN POSSIBILITIES.</span><h1>Make it move.<br/><em>Make it yours.</em></h1><p>Little interactions. Living illustrations. Interfaces with a pulse. Build motion that belongs to you—with a visual studio and a toolkit made for code.</p><div className="hero-actions"><a className="button button-dark" href="/studio/">Start creating <span>↗</span></a><a className="text-link" href="/docs/">Meet the toolkit <span>→</span></a></div><div className="install"><code>npm install motion-forge</code><button aria-label="Copy install command" onClick={async e => { const button = e.currentTarget; try { await navigator.clipboard.writeText('npm install motion-forge'); button.textContent = 'Copied'; } catch { button.textContent = 'Select & copy'; } }}>Copy</button></div><small className="local-note">Local preview · Package not yet published · MIT licensed</small></div><Showcase id="scout" hero/></section>
    <div className="principles"><span>DRAW IT. KEYFRAME IT. SHIP IT.</span><span>Editable by humans & agents</span><span>Portable JSON + SVG</span><span>Your work stays yours</span></div>
    <section className="section intro"><div><span className="eyebrow">01 / A LITTLE MORE ALIVE</span><h2>Beyond the<br/><em>play button.</em></h2></div><p>Motion should respond. Connect an input, trigger an event, or change a state. The same animation can welcome someone, celebrate a small win, or turn a number into something you can feel.</p></section>
    <div className="demo-grid"><div><Showcase id="made-it"/><div className="demo-caption"><h3>Made it.</h3><p>Feedback worth feeling. Springs, strokes, and a tiny celebration.</p></div></div><div><Showcase id="signal"/><div className="demo-caption"><h3>Signal.</h3><p>One input. Two bindings. A graphic that follows your data.</p></div></div></div>
    <section className="workflow section"><div><span className="eyebrow">02 / TWO WAYS IN. ONE SOURCE.</span><h2>Craft by hand.<br/><em>Compose with code.</em></h2><p>Your animation is a versioned, typed document. Open it in Studio, generate it with an agent, review the diff, and play it in your app.</p><a className="text-link" href="/docs/">See the document format →</a></div><div className="code-card"><div><span>Animation.tsx</span><span>REACT / TYPESCRIPT</span></div><pre><code>{`import { MotionForge } from 'motion-forge/react';\nimport { createPreset } from 'motion-forge/presets';\n\nconst scout = createPreset('scout');\n\nexport function Welcome() {\n  return <MotionForge document={scout} />;\n}`}</code></pre><footer><i/> Same document. Studio, React, CLI.</footer></div></section>
    <section className="feature-grid"><article><span>01</span><h3>Precisely yours.</h3><p>Keyframes, custom curves, and springs. Tune a detail until it feels right.</p></article><article><span>02</span><h3>Small parts. Real control.</h3><p>A pure animation engine with React bindings. Bring your own clock or use ours.</p></article><article><span>03</span><h3>Made to leave.</h3><p>Take the editable document, SVG, PNG, or React component with you.</p></article></section>
    <section className="closing"><span className="eyebrow">A BLANK CANVAS IS A GOOD START.</span><h2>What will you<br/><em>bring to life?</em></h2><a className="button button-dark" href="/studio/">Open Motion Forge Studio <span>↗</span></a><p>No signup. No upload. Just you and the canvas.</p></section></>;
}
function Examples() { return <main className="examples-page"><span className="eyebrow">THE PLAYGROUND</span><h1>A few starting<br/><em>points.</em></h1><p>Original, interactive, and fully editable. Open Studio’s example picker to make one your own.</p><div className="examples-grid">{presetCatalog.map(p => <article key={p.id}><Showcase id={p.id}/><h2>{p.name}</h2><p>{p.description}</p><a className="text-link" href="/studio/">Open Studio →</a></article>)}</div></main>; }
export function App({ path }: { path: string }) {
  if (path.startsWith('/studio')) return <Suspense fallback={<main className="studio-loading"><Brand/><p>Opening your studio…</p></main>}><StudioRoute/></Suspense>;
  return <div className="site-shell"><a className="skip-link" href="#content">Skip to content</a><Navigation path={path}/><div id="content">{path.startsWith('/examples') ? <Examples/> : path.startsWith('/docs') ? <Docs path={path}/> : path === '/' ? <Home/> : <main className="examples-page"><h1>Page not found.</h1><p>This canvas is empty. <a href="/">Return home →</a></p></main>}</div><footer className="site-footer"><Brand/><span>Open source. Made for making.</span><div><a href="/docs/">Docs</a><a href="/examples/">Examples</a><a href="/studio/">Studio ↗</a></div></footer></div>;
}
