import type { AnimatedProperty, ForgeDocument, ForgeNode } from '../core/schema';
import { ColorField, NumberField, SelectField, TextField } from './fields';
import type { Edit } from './timeline';

export function Inspector({ document, node, edit, patch, animated }: { document: ForgeDocument; node?: ForgeNode; edit: Edit; patch: (patch: Partial<ForgeNode>) => void; animated: Set<AnimatedProperty> }) {
  const numeric = (property: keyof ForgeNode, label: string, min?: number, max?: number) => <NumberField key={property} label={`${label}${animated.has(property as AnimatedProperty) ? ' ◇' : ''}`} value={node![property] as number} onChange={value => patch({ [property]: value })} min={min} max={max} step={property === 'opacity' || property.startsWith('scale') ? 0.1 : 1} disabled={node!.locked}/>;
  if (!node) return <div className="mf-inspector"><div className="mf-section-title">ARTBOARD</div><TextField label="Name" value={document.name} onChange={name => edit('Rename document', d => { d.name = name; })}/><div className="mf-grid-two"><NumberField label="Width" value={document.width} min={1} max={8192} onChange={width => edit('Resize artboard', d => { d.width = Math.round(width); })}/><NumberField label="Height" value={document.height} min={1} max={8192} onChange={height => edit('Resize artboard', d => { d.height = Math.round(height); })}/></div><ColorField label="Background" value={document.background} onChange={value => edit('Artboard color', d => { d.background = value; })}/><p className="mf-hint">Select a layer to style it. Drag directly on the artboard to move it.</p><p className="mf-hint">Space to play · ⌘/Ctrl Z to undo<br/>Arrows to nudge · Shift for 10px</p></div>;
  return <div className="mf-inspector"><div className="mf-section-title">{node.type.toUpperCase()}<span>{node.locked ? 'LOCKED' : 'PROPERTIES'}</span></div><fieldset disabled={node.locked}><TextField label="Layer name" value={node.name} onChange={name => patch({ name })}/><SelectField label="Parent" value={node.parentId ?? ''} onChange={parentId => patch({ parentId: parentId || undefined })}><option value="">Artboard</option>{document.nodes.filter(n => n.type === 'group' && n.id !== node.id).map(n => <option key={n.id} value={n.id}>{n.name}</option>)}</SelectField><div className="mf-section-title">TRANSFORM</div><div className="mf-grid-two">{numeric('x', 'X')}{numeric('y', 'Y')}{numeric('rotation', 'Rotation')}{numeric('opacity', 'Opacity', 0, 1)}{numeric('scaleX', 'Scale X', -100, 100)}{numeric('scaleY', 'Scale Y', -100, 100)}{numeric('originX', 'Origin X')}{numeric('originY', 'Origin Y')}</div>
    {node.type === 'rect' ? <><div className="mf-section-title">GEOMETRY</div><div className="mf-grid-two">{numeric('width', 'Width', 0)}{numeric('height', 'Height', 0)}{numeric('radius', 'Radius', 0)}</div></> : null}
    {node.type === 'ellipse' ? <div className="mf-grid-two">{numeric('rx', 'Radius X', 0)}{numeric('ry', 'Radius Y', 0)}</div> : null}
    {node.type === 'line' ? <div className="mf-grid-two">{numeric('x2', 'End X')}{numeric('y2', 'End Y')}</div> : null}
    {node.type === 'path' ? <TextField label="Path data" value={node.d} onChange={d => patch({ d })}/> : null}
    {node.type === 'text' ? <><TextField label="Text" value={node.text} onChange={text => patch({ text })}/>{numeric('fontSize', 'Font size', 1, 1000)}<SelectField label="Typeface" value={node.fontFamily} onChange={fontFamily => patch({ fontFamily: fontFamily as ForgeNode['fontFamily'] })}>{['sans-serif', 'serif', 'monospace'].map(v => <option key={v}>{v}</option>)}</SelectField><SelectField label="Weight" value={node.fontWeight} onChange={fontWeight => patch({ fontWeight: fontWeight as ForgeNode['fontWeight'] })}>{['400', '500', '600', '700', '800'].map(v => <option key={v}>{v}</option>)}</SelectField><SelectField label="Alignment" value={node.textAnchor} onChange={textAnchor => patch({ textAnchor: textAnchor as ForgeNode['textAnchor'] })}>{['start', 'middle', 'end'].map(v => <option key={v}>{v}</option>)}</SelectField></> : null}
    <div className="mf-section-title">APPEARANCE</div><ColorField label="Fill" value={node.fill} onChange={fill => patch({ fill })}/><ColorField label="Stroke" value={node.stroke} onChange={stroke => patch({ stroke })}/>{numeric('strokeWidth', 'Stroke width', 0, 1000)}<TextField label="Dash pattern" value={node.strokeDasharray} onChange={strokeDasharray => patch({ strokeDasharray })}/>{numeric('strokeDashoffset', 'Dash offset')}
    <p className="mf-hint">◇ Animated properties update a key at the playhead. Input bindings override their matching animation properties.</p>
  </fieldset></div>;
}
