import { useState } from 'react';
import type { ForgeDocument, ForgeInput, Binding, Transition } from '../core/schema';
import { numericProperties } from '../core/schema';
import { uniqueId } from '../core/history';
import type { ForgePlayer } from '../core/player';
import type { Edit } from './timeline';
import { Icon, NumberField, SelectField, TextField } from './fields';

export function Machine({ document, edit, stateId, chooseState, player, selected }: { document: ForgeDocument; edit: Edit; stateId: string; chooseState: (id: string) => void; player: ForgePlayer; selected: string }) {
  const [tab, setTab] = useState<'states' | 'inputs'>('states');
  const [triggerType, setTriggerType] = useState<'event' | 'input' | 'complete'>('event');
  const [event, setEvent] = useState('activate'), [target, setTarget] = useState('');
  const [inputId, setInputId] = useState(''), [operator, setOperator] = useState<'eq' | 'gt' | 'gte' | 'lt' | 'lte'>('eq'), [condition, setCondition] = useState('true');
  const [bindingInput, setBindingInput] = useState(''), [bindingProperty, setBindingProperty] = useState<Binding['property']>('x');
  const [inputType, setInputType] = useState<'number' | 'boolean'>('number');
  const state = document.states.find(s => s.id === stateId) ?? document.states[0]!;
  const clip = document.clips.find(c => c.id === state.clipId)!;
  const addState = () => {
    let id = '';
    edit('Add state and animation', d => { id = uniqueId(d.states.map(s => s.id), 'state'); const clipId = uniqueId(d.clips.map(c => c.id), 'animation'); d.clips.push({ id: clipId, name: `Animation ${d.clips.length + 1}`, duration: 2000, tracks: [] }); d.states.push({ id, name: `State ${d.states.length + 1}`, clipId, loop: false }); }); if (id) chooseState(id);
  };
  const changeInput = (id: string, patch: Partial<ForgeInput>) => edit('Edit input', d => { Object.assign(d.inputs.find(i => i.id === id)!, patch); });
  const addTransition = () => edit('Add transition', d => {
    const input = d.inputs.find(i => i.id === inputId);
    let trigger: Transition['trigger'] = { type: 'complete' };
    if (triggerType === 'event') trigger = { type: 'event', event };
    if (triggerType === 'input') { if (!input) throw new Error('Select a condition input'); if (input.type === 'number' && (!condition.trim() || !Number.isFinite(Number(condition)))) throw new Error('Enter a finite numeric condition'); if (input.type === 'boolean' && !['true', 'false'].includes(condition)) throw new Error('Boolean conditions must be true or false'); trigger = { type: 'input', inputId, operator: input.type === 'boolean' ? 'eq' : operator, value: input.type === 'boolean' ? condition === 'true' : Number(condition) }; }
    d.transitions.push({ id: uniqueId(d.transitions.map(t => t.id), 'transition'), from: state.id, to: target, trigger, duration: 250, easing: 'ease-in-out' });
  });
  const addBinding = () => edit('Bind input to layer', d => { if (!selected) throw new Error('Select a layer to bind'); d.bindings.push({ id: uniqueId(d.bindings.map(b => b.id), 'binding'), inputId: bindingInput, nodeId: selected, property: bindingProperty, from: bindingProperty === 'fontSize' ? 1 : 0, to: bindingProperty === 'opacity' || bindingProperty.startsWith('scale') ? 1 : 100 }); });
  return <div className="mf-machine"><div className="mf-tabs"><button className={tab === 'states' ? 'is-active' : ''} onClick={() => setTab('states')}>States</button><button className={tab === 'inputs' ? 'is-active' : ''} onClick={() => setTab('inputs')}>Inputs</button></div>
    {tab === 'states' ? <><div className="mf-section-title">STATE MACHINE<button className="mf-icon" onClick={addState} aria-label="Add state"><Icon name="plus"/></button></div><div className="mf-state-list">{document.states.map(s => <button key={s.id} className={s.id === state.id ? 'is-active' : ''} onClick={() => chooseState(s.id)}><span className="mf-state-dot"/>{s.name}{s.id === document.initialState ? <small>initial</small> : null}</button>)}</div>
      <TextField label="State name" value={state.name} onChange={name => edit('Rename state', d => { d.states.find(s => s.id === state.id)!.name = name; })}/><SelectField label="Animation" value={state.clipId} onChange={clipId => edit('Assign animation', d => { d.states.find(s => s.id === state.id)!.clipId = clipId; })}>{document.clips.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><TextField label="Animation name" value={clip.name} onChange={name => edit('Rename animation', d => { d.clips.find(c => c.id === clip.id)!.name = name; })}/><NumberField label="Duration · ms" value={clip.duration} min={1} max={600000} onChange={duration => edit('Change duration', d => { d.clips.find(c => c.id === clip.id)!.duration = duration; })}/><label className="mf-check"><input type="checkbox" checked={state.loop} onChange={e => edit('Set loop', d => { d.states.find(s => s.id === state.id)!.loop = e.target.checked; })}/> Loop animation</label>
      <div className="mf-button-row"><button disabled={state.id === document.initialState} onClick={() => edit('Set initial state', d => { d.initialState = state.id; })}>Make initial</button><button disabled={document.states.length === 1} onClick={() => { edit('Delete state', d => { d.states = d.states.filter(s => s.id !== state.id); d.transitions = d.transitions.filter(t => t.from !== state.id && t.to !== state.id); if (d.initialState === state.id) d.initialState = d.states[0]!.id; }); chooseState(document.states.find(s => s.id !== state.id)!.id); }}>Delete state</button></div>
      <div className="mf-section-title">TRANSITIONS</div>{document.transitions.filter(t => t.from === state.id || t.from === '*').map(t => <div className="mf-transition" key={t.id}><strong>→ {document.states.find(s => s.id === t.to)?.name}</strong><button className="mf-icon" aria-label={`Delete transition ${t.id}`} onClick={() => edit('Delete transition', d => { d.transitions = d.transitions.filter(v => v.id !== t.id); })}><Icon name="trash"/></button><small>{t.trigger.type === 'event' ? `Event: ${t.trigger.event}` : t.trigger.type === 'complete' ? 'On completion' : `${t.trigger.inputId} ${t.trigger.operator} ${String(t.trigger.value)}`}</small><NumberField label="Blend · ms" value={t.duration} min={0} max={10000} onChange={duration => edit('Transition duration', d => { d.transitions.find(v => v.id === t.id)!.duration = duration; })}/>{t.trigger.type === 'event' ? <button onClick={() => { if (t.trigger.type === 'event') player.send(t.trigger.event); }}>Preview “{t.trigger.event}”</button> : null}</div>)}
      <details className="mf-add-panel"><summary>Add transition</summary><SelectField label="To state" value={target} onChange={setTarget}><option value="">Choose target</option>{document.states.filter(s => s.id !== state.id).map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</SelectField><SelectField label="Trigger" value={triggerType} onChange={v => setTriggerType(v as typeof triggerType)}><option value="event">Event</option><option value="input">Input condition</option><option value="complete">Completion</option></SelectField>{triggerType === 'event' ? <label className="mf-field"><span>Event name</span><input value={event} onChange={e => setEvent(e.target.value)}/></label> : null}{triggerType === 'input' ? <><SelectField label="Input" value={inputId} onChange={v => { setInputId(v); setCondition(document.inputs.find(i => i.id === v)?.type === 'number' ? '50' : 'true'); }}><option value="">Choose input</option>{document.inputs.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Operator" value={operator} onChange={v => setOperator(v as typeof operator)}>{['eq', 'gt', 'gte', 'lt', 'lte'].map(v => <option key={v}>{v}</option>)}</SelectField><label className="mf-field"><span>Condition value</span><input value={condition} onChange={e => setCondition(e.target.value)}/></label></> : null}<button disabled={!target} onClick={addTransition}><Icon name="plus"/> Create transition</button></details>
    </> : <><div className="mf-section-title">LIVE INPUTS</div>{document.inputs.length ? document.inputs.map(input => <div className="mf-input-card" key={input.id}><strong>{input.name}</strong><small>{input.id} · {input.type}</small>{input.type === 'number' ? <label className="mf-field"><span>Preview · {String(player.getSnapshot().inputs[input.id])}</span><input type="range" aria-label={`Preview ${input.name}`} min={input.min} max={input.max} step={(input.max - input.min) / 100} value={Number(player.getSnapshot().inputs[input.id] ?? input.default)} onChange={e => player.setInput(input.id, Number(e.target.value))}/></label> : <label className="mf-check"><input type="checkbox" checked={Boolean(player.getSnapshot().inputs[input.id])} onChange={e => player.setInput(input.id, e.target.checked)}/> Preview {input.name}</label>}
      <details><summary>Edit input</summary><TextField label="Input name" value={input.name} onChange={name => changeInput(input.id, { name })}/>{input.type === 'number' ? <><NumberField label="Minimum" value={input.min} onChange={min => changeInput(input.id, { min })}/><NumberField label="Maximum" value={input.max} onChange={max => changeInput(input.id, { max })}/><NumberField label="Default" value={input.default} onChange={value => changeInput(input.id, { default: value })}/></> : <label className="mf-check"><input type="checkbox" checked={input.default} onChange={e => changeInput(input.id, { default: e.target.checked })}/> Default on</label>}<button onClick={() => edit('Delete input and references', d => { d.inputs = d.inputs.filter(i => i.id !== input.id); d.bindings = d.bindings.filter(b => b.inputId !== input.id); d.transitions = d.transitions.filter(t => t.trigger.type !== 'input' || t.trigger.inputId !== input.id); })}>Delete input</button></details></div>) : <p className="mf-hint">Inputs connect your animation to application data.</p>}
      <div className="mf-button-row"><select aria-label="New input type" value={inputType} onChange={e => setInputType(e.target.value as typeof inputType)}><option value="number">Number</option><option value="boolean">Boolean</option></select><button onClick={() => edit('Add input', d => { const id = uniqueId(d.inputs.map(i => i.id), 'input'); d.inputs.push(inputType === 'number' ? { id, name: `Input ${d.inputs.length + 1}`, type: 'number', min: 0, max: 100, default: 50 } : { id, name: `Input ${d.inputs.length + 1}`, type: 'boolean', default: false }); })}><Icon name="plus"/> Input</button></div>
      <div className="mf-section-title">PROPERTY BINDINGS</div>{document.bindings.map(b => <details key={b.id} className="mf-binding"><summary>{b.inputId} → {b.nodeId}.{b.property}</summary><div className="mf-grid-two"><NumberField label="From" value={b.from} onChange={from => edit('Binding range', d => { d.bindings.find(v => v.id === b.id)!.from = from; })}/><NumberField label="To" value={b.to} onChange={to => edit('Binding range', d => { d.bindings.find(v => v.id === b.id)!.to = to; })}/></div><button onClick={() => edit('Remove binding', d => { d.bindings = d.bindings.filter(v => v.id !== b.id); })}>Remove binding</button></details>)}
      <details className="mf-add-panel"><summary>Bind selected layer</summary><p className="mf-hint">Layer: {document.nodes.find(n => n.id === selected)?.name ?? 'Select a layer first'}</p><SelectField label="Numeric input" value={bindingInput} onChange={setBindingInput}><option value="">Choose input</option>{document.inputs.filter(i => i.type === 'number').map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</SelectField><SelectField label="Property" value={bindingProperty} onChange={v => setBindingProperty(v as Binding['property'])}>{numericProperties.map(p => <option key={p}>{p}</option>)}</SelectField><button disabled={!selected || !bindingInput} onClick={addBinding}>Create binding</button></details>
    </>}
  </div>;
}
